create extension if not exists supabase_vault with schema vault;

create table if not exists public.app_settings (
    key text primary key,
    value jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now(),
    updated_by text not null default 'system'
);

create table if not exists public.crm_provider_configs (
    provider text primary key check (provider in ('amocrm', 'bitrix24')),
    settings jsonb not null default '{}'::jsonb,
    secret_id uuid,
    has_secret boolean not null default false,
    connection_status text not null default 'not_checked'
        check (connection_status in ('not_checked', 'ok', 'error')),
    connection_message text not null default '',
    connection_checked_at timestamptz,
    updated_at timestamptz not null default now(),
    updated_by text not null default 'system'
);

create table if not exists public.crm_delivery_log (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    provider text not null,
    event text not null,
    status text not null,
    message text not null default '',
    lead_reference text,
    idempotency_key text
);

create unique index if not exists crm_delivery_log_idempotency_idx
    on public.crm_delivery_log (idempotency_key)
    where idempotency_key is not null;

alter table public.app_settings enable row level security;
alter table public.crm_provider_configs enable row level security;
alter table public.crm_delivery_log enable row level security;

revoke all on public.app_settings from anon, authenticated;
revoke all on public.crm_provider_configs from anon, authenticated;
revoke all on public.crm_delivery_log from anon, authenticated;

insert into public.app_settings (key, value, updated_by)
values (
    'runtime',
    '{
      "active_provider": "off",
      "customer_delivery_format": "pptx",
      "test_mode": true,
      "telegram_diagnostics_enabled": true,
      "telegram_send_lead_summary": true,
      "telegram_send_sales_playbook": true,
      "telegram_send_customer_report": true,
      "telegram_lead_template": "",
      "telegram_sales_caption": "[{app}] Sales playbook: {company}",
      "telegram_customer_caption": "[{app}] Клиентское заключение: {company}"
    }'::jsonb,
    'migration'
)
on conflict (key) do nothing;

create or replace function public.admin_save_crm_provider_config(
    p_provider text,
    p_settings jsonb,
    p_secret text,
    p_updated_by text
)
returns void
language plpgsql
security definer
set search_path = public, vault
as $$
declare
    current_secret_id uuid;
begin
    if p_provider not in ('amocrm', 'bitrix24') then
        raise exception 'Unsupported CRM provider';
    end if;

    select secret_id into current_secret_id
    from public.crm_provider_configs
    where provider = p_provider;

    if p_secret is not null and length(trim(p_secret)) > 0 then
        if current_secret_id is null then
            current_secret_id := vault.create_secret(
                p_secret,
                'audit_crm_' || p_provider,
                'Encrypted CRM credentials managed by the audit admin console'
            );
        else
            perform vault.update_secret(
                current_secret_id,
                p_secret,
                'audit_crm_' || p_provider,
                'Encrypted CRM credentials managed by the audit admin console'
            );
        end if;
    end if;

    insert into public.crm_provider_configs (
        provider,
        settings,
        secret_id,
        has_secret,
        connection_status,
        connection_message,
        connection_checked_at,
        updated_at,
        updated_by
    ) values (
        p_provider,
        coalesce(p_settings, '{}'::jsonb),
        current_secret_id,
        current_secret_id is not null,
        'not_checked',
        '',
        null,
        now(),
        coalesce(nullif(p_updated_by, ''), 'admin')
    )
    on conflict (provider) do update set
        settings = excluded.settings,
        secret_id = coalesce(excluded.secret_id, crm_provider_configs.secret_id),
        has_secret = coalesce(excluded.secret_id, crm_provider_configs.secret_id) is not null,
        connection_status = 'not_checked',
        connection_message = '',
        connection_checked_at = null,
        updated_at = now(),
        updated_by = excluded.updated_by;
end;
$$;

create or replace function public.admin_get_crm_provider_secret(p_provider text)
returns table(provider text, secret_value text)
language sql
security definer
set search_path = public, vault
as $$
    select c.provider, v.decrypted_secret
    from public.crm_provider_configs c
    join vault.decrypted_secrets v on v.id = c.secret_id
    where c.provider = p_provider;
$$;

create or replace function public.admin_activate_crm_provider(
    p_provider text,
    p_updated_by text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    current_value jsonb;
begin
    if p_provider not in ('off', 'amocrm', 'bitrix24') then
        raise exception 'Unsupported CRM provider';
    end if;

    if p_provider <> 'off' and not exists (
        select 1
        from public.crm_provider_configs
        where provider = p_provider
          and connection_status = 'ok'
          and has_secret = true
    ) then
        raise exception 'CRM connection must pass validation before activation';
    end if;

    select value into current_value
    from public.app_settings
    where key = 'runtime';

    current_value := coalesce(current_value, '{}'::jsonb)
        || jsonb_build_object('active_provider', p_provider);

    insert into public.app_settings (key, value, updated_at, updated_by)
    values ('runtime', current_value, now(), coalesce(nullif(p_updated_by, ''), 'admin'))
    on conflict (key) do update set
        value = excluded.value,
        updated_at = excluded.updated_at,
        updated_by = excluded.updated_by;

    return current_value;
end;
$$;

revoke all on function public.admin_save_crm_provider_config(text, jsonb, text, text)
    from public, anon, authenticated;
revoke all on function public.admin_get_crm_provider_secret(text)
    from public, anon, authenticated;
revoke all on function public.admin_activate_crm_provider(text, text)
    from public, anon, authenticated;

grant execute on function public.admin_save_crm_provider_config(text, jsonb, text, text)
    to service_role;
grant execute on function public.admin_get_crm_provider_secret(text)
    to service_role;
grant execute on function public.admin_activate_crm_provider(text, text)
    to service_role;
